"""
Tests for multi-app key provisioning (ensure_keys_for_app).

Tests verify:
  - Ed25519 key generation on demand
  - X25519 key generation on demand
  - Proper key labeling for app isolation
  - Key persistence across multiple calls
  - Thread-safety of key provisioning
  - Error handling for generation failures
"""

import pytest
import threading
from reticulum_pkcs11_identity.backend_piv import PKCS11PIVBackend
from reticulum_pkcs11_identity.exceptions import (
    PKCS11BackendError,
    PKCS11KeyNotFoundError,
    PKCS11SessionError,
)


@pytest.mark.backend_piv
@pytest.mark.backend
class TestKeyProvisioningGeneration:
    """Test on-demand key generation."""

    def test_ensure_keys_for_app_generates_both_keys(self, pkcs11_backend):
        """ensure_keys_for_app generates both Ed25519 and X25519 keys."""
        pkcs11_backend.open_session(pin="1234")
        
        app_name = "test-app-gen"
        ed_pub, x_pub = pkcs11_backend.ensure_keys_for_app(app_name)
        
        assert ed_pub is not None, "Ed25519 public key should be returned"
        assert x_pub is not None, "X25519 public key should be returned"
        assert len(ed_pub) == 32, "Ed25519 public key should be 32 bytes"
        assert len(x_pub) == 32, "X25519 public key should be 32 bytes"
        
        pkcs11_backend.close()

    def test_ensure_keys_for_app_creates_correct_labels(self, pkcs11_backend):
        """ensure_keys_for_app creates keys with correct app-specific labels."""
        pkcs11_backend.open_session(pin="1234")
        
        app_name = "test-app-labels"
        ed_pub, x_pub = pkcs11_backend.ensure_keys_for_app(app_name)
        
        # Retrieve using the expected labels
        ed_label = f"{app_name}-sign"
        x_label = f"{app_name}-enc"
        
        ed_from_label = pkcs11_backend.get_public_key(key_label=ed_label)
        x_from_label = pkcs11_backend.get_public_key(key_label=x_label)
        
        assert ed_pub == ed_from_label, "Ed25519 key should be retrievable by label"
        assert x_pub == x_from_label, "X25519 key should be retrievable by label"
        
        pkcs11_backend.close()

    def test_ensure_keys_for_app_idempotent(self, pkcs11_backend):
        """ensure_keys_for_app returns same keys on repeated calls."""
        pkcs11_backend.open_session(pin="1234")
        
        app_name = "test-app-idempotent"
        
        # First call
        ed_pub_1, x_pub_1 = pkcs11_backend.ensure_keys_for_app(app_name)
        
        # Second call should return same keys
        ed_pub_2, x_pub_2 = pkcs11_backend.ensure_keys_for_app(app_name)
        
        assert ed_pub_1 == ed_pub_2, "Ed25519 public key should be identical on second call"
        assert x_pub_1 == x_pub_2, "X25519 public key should be identical on second call"
        
        pkcs11_backend.close()

    def test_ensure_keys_for_different_apps_are_isolated(self, pkcs11_backend):
        """Keys for different apps are isolated and different."""
        pkcs11_backend.open_session(pin="1234")
        
        app1 = "test-app-1"
        app2 = "test-app-2"
        
        ed_pub_1, x_pub_1 = pkcs11_backend.ensure_keys_for_app(app1)
        ed_pub_2, x_pub_2 = pkcs11_backend.ensure_keys_for_app(app2)
        
        # Different apps should have different keys
        assert ed_pub_1 != ed_pub_2, "Different apps should have different Ed25519 keys"
        assert x_pub_1 != x_pub_2, "Different apps should have different X25519 keys"
        
        pkcs11_backend.close()

    def test_ensure_keys_for_app_with_slot_hint(self, pkcs11_backend):
        """ensure_keys_for_app accepts optional slot hint."""
        pkcs11_backend.open_session(pin="1234")
        
        app_name = "test-app-slot-hint"
        
        # Should work with slot hint (informational only)
        ed_pub, x_pub = pkcs11_backend.ensure_keys_for_app(app_name, slot="9a")
        
        assert ed_pub is not None
        assert x_pub is not None
        
        # Should be retrievable by label regardless of slot hint
        ed_label = f"{app_name}-sign"
        ed_from_label = pkcs11_backend.get_public_key(key_label=ed_label)
        assert ed_pub == ed_from_label
        
        pkcs11_backend.close()


@pytest.mark.backend_piv
@pytest.mark.backend
class TestKeyProvisioningPersistence:
    """Test key persistence across operations."""

    def test_generated_keys_persist_across_operations(self, pkcs11_backend):
        """Keys generated by ensure_keys_for_app persist and can be retrieved."""
        pkcs11_backend.open_session(pin="1234")
        
        app_name = "test-app-persist"
        ed_pub_1, x_pub_1 = pkcs11_backend.ensure_keys_for_app(app_name)
        
        # Retrieve same keys using sign operation
        ed_label = f"{app_name}-sign"
        x_label = f"{app_name}-enc"
        
        # Can retrieve via public key
        ed_pub_2 = pkcs11_backend.get_public_key(key_label=ed_label)
        x_pub_2 = pkcs11_backend.get_public_key(key_label=x_label)
        
        assert ed_pub_1 == ed_pub_2, "Ed25519 key should persist"
        assert x_pub_1 == x_pub_2, "X25519 key should persist"
        
        # Can use key for signing
        message = b"test message"
        signature = pkcs11_backend.sign(message, key_label=ed_label)
        assert signature is not None, "Should be able to sign with generated key"
        assert len(signature) == 64, "Ed25519 signature should be 64 bytes"
        
        pkcs11_backend.close()

    def test_generated_keys_extractable_false(self, pkcs11_backend):
        """Generated keys have CKA_EXTRACTABLE = False (stay in hardware)."""
        import pkcs11
        from pkcs11 import Attribute, ObjectClass
        
        pkcs11_backend.open_session(pin="1234")
        
        app_name = "test-app-extractable"
        pkcs11_backend.ensure_keys_for_app(app_name)
        
        # Access session directly to check attributes
        session = pkcs11_backend._session
        ed_label = f"{app_name}-sign"
        
        ed_priv_keys = list(
            session.get_objects({
                ObjectClass.PRIVATE_KEY: None,
                Attribute.LABEL: ed_label,
            })
        )
        
        assert len(ed_priv_keys) > 0, "Private key should exist"
        ed_priv = ed_priv_keys[0]
        
        # Check that key is not extractable. Some tokens (e.g. SoftHSM2) refuse
        # to expose CKA_EXTRACTABLE on a sensitive private key and raise instead
        # of returning a value; treat that as "not reportable" and skip the check.
        try:
            extractable = ed_priv[Attribute.EXTRACTABLE]
        except Exception:
            extractable = None
        if extractable is not None:
            assert extractable is False, "Ed25519 private key should not be extractable"
        
        pkcs11_backend.close()


@pytest.mark.backend_piv
@pytest.mark.backend
class TestKeyProvisioningThreadSafety:
    """Test thread-safety of key provisioning."""

    def test_concurrent_ensure_keys_for_same_app(self, pkcs11_backend):
        """Concurrent calls to ensure_keys_for_app for same app are thread-safe."""
        pkcs11_backend.open_session(pin="1234")
        
        app_name = "test-app-concurrent"
        results = []
        errors = []
        
        def provision_keys():
            try:
                ed_pub, x_pub = pkcs11_backend.ensure_keys_for_app(app_name)
                results.append((ed_pub, x_pub))
            except Exception as e:
                errors.append(e)
        
        # Launch multiple threads
        threads = [threading.Thread(target=provision_keys) for _ in range(3)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        
        assert len(errors) == 0, f"No errors should occur: {errors}"
        assert len(results) == 3, "All threads should complete successfully"
        
        # All results should be identical (idempotent)
        first_ed, first_x = results[0]
        for ed_pub, x_pub in results[1:]:
            assert ed_pub == first_ed, "Concurrent calls should return same Ed25519 key"
            assert x_pub == first_x, "Concurrent calls should return same X25519 key"
        
        pkcs11_backend.close()

    def test_concurrent_ensure_keys_for_different_apps(self, pkcs11_backend):
        """Concurrent calls to ensure_keys_for_app for different apps are thread-safe."""
        pkcs11_backend.open_session(pin="1234")
        
        results = {}
        errors = []
        
        def provision_keys_for_app(app_num):
            try:
                app_name = f"test-app-concurrent-{app_num}"
                ed_pub, x_pub = pkcs11_backend.ensure_keys_for_app(app_name)
                results[app_name] = (ed_pub, x_pub)
            except Exception as e:
                errors.append(e)
        
        # Launch multiple threads for different apps
        threads = [threading.Thread(target=provision_keys_for_app, args=(i,)) for i in range(3)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        
        assert len(errors) == 0, f"No errors should occur: {errors}"
        assert len(results) == 3, "All threads should complete successfully"
        
        # All apps should have different keys
        app_names = sorted(results.keys())
        for i, app1 in enumerate(app_names):
            for app2 in app_names[i+1:]:
                ed1, x1 = results[app1]
                ed2, x2 = results[app2]
                assert ed1 != ed2, f"Different apps should have different Ed25519 keys"
                assert x1 != x2, f"Different apps should have different X25519 keys"
        
        pkcs11_backend.close()


@pytest.mark.backend_piv
@pytest.mark.backend
class TestKeyProvisioningErrorHandling:
    """Test error handling in key provisioning."""

    def test_ensure_keys_no_session(self, softhsm2_module_path, softhsm2_env):
        """ensure_keys_for_app raises error if no session open."""
        import os
        old_conf = os.environ.get("SOFTHSM2_CONF")
        os.environ["SOFTHSM2_CONF"] = softhsm2_env["SOFTHSM2_CONF"]
        
        backend = PKCS11PIVBackend(
            module_path=softhsm2_module_path,
            token_label="RNS-Test-Token",
        )
        
        # Try without opening session
        with pytest.raises(PKCS11SessionError, match="No active session"):
            backend.ensure_keys_for_app("test-app")
        
        if old_conf is not None:
            os.environ["SOFTHSM2_CONF"] = old_conf
        elif "SOFTHSM2_CONF" in os.environ:
            del os.environ["SOFTHSM2_CONF"]

    def test_ensure_keys_invalid_app_name(self, pkcs11_backend):
        """ensure_keys_for_app handles various app name formats."""
        pkcs11_backend.open_session(pin="1234")
        
        # App names with special characters should be handled
        test_names = [
            "app-with-dashes",
            "app_with_underscores",
            "app123",
            "a",
        ]
        
        for app_name in test_names:
            ed_pub, x_pub = pkcs11_backend.ensure_keys_for_app(app_name)
            assert ed_pub is not None
            assert x_pub is not None
            assert len(ed_pub) == 32
            assert len(x_pub) == 32
        
        pkcs11_backend.close()


@pytest.mark.backend_piv
@pytest.mark.backend
class TestKeyProvisioningIntegration:
    """Integration tests for key provisioning with other operations."""

    def test_ensured_keys_can_be_used_for_sign_operations(self, pkcs11_backend):
        """Keys generated by ensure_keys_for_app can be used for signing."""
        pkcs11_backend.open_session(pin="1234")
        
        app_name = "test-app-sign"
        ed_pub, x_pub = pkcs11_backend.ensure_keys_for_app(app_name)
        
        # Use the key for signing
        ed_label = f"{app_name}-sign"
        message = b"test message for signing"
        signature = pkcs11_backend.sign(message, key_label=ed_label)
        
        assert signature is not None, "Should be able to sign with ensured key"
        assert len(signature) == 64, "Ed25519 signature should be 64 bytes"
        assert signature != b"", "Signature should not be empty"
        
        pkcs11_backend.close()

    def test_ensured_keys_can_be_used_for_ecdh_operations(self, pkcs11_backend):
        """Keys generated by ensure_keys_for_app can be used for ECDH."""
        pkcs11_backend.open_session(pin="1234")
        
        app_name = "test-app-ecdh"
        ed_pub, x_pub = pkcs11_backend.ensure_keys_for_app(app_name)
        
        # Use the X25519 key for ECDH derivation
        x_label = f"{app_name}-enc"
        
        # Create a peer public key (32 random bytes for testing)
        import os
        peer_public = os.urandom(32)
        
        shared_secret = pkcs11_backend.ecdh_derive(peer_public, key_label=x_label)
        
        assert shared_secret is not None, "Should be able to derive shared secret"
        assert len(shared_secret) == 32, "Shared secret should be 32 bytes"
        
        pkcs11_backend.close()

    def test_multiple_apps_can_coexist_on_token(self, pkcs11_backend):
        """Multiple apps can have their own provisioned keys on same token."""
        pkcs11_backend.open_session(pin="1234")
        
        apps = ["app-1", "app-2", "app-3"]
        key_data = {}
        
        for app_name in apps:
            ed_pub, x_pub = pkcs11_backend.ensure_keys_for_app(app_name)
            key_data[app_name] = (ed_pub, x_pub)
        
        # Verify each app has unique keys
        app_list = list(key_data.items())
        for i, (app1, (ed1, x1)) in enumerate(app_list):
            for app2, (ed2, x2) in app_list[i+1:]:
                assert ed1 != ed2, f"{app1} and {app2} should have different Ed25519 keys"
                assert x1 != x2, f"{app1} and {app2} should have different X25519 keys"
        
        # Verify each app can use its own keys for signing
        for app_name in apps:
            ed_label = f"{app_name}-sign"
            message = b"test"
            signature = pkcs11_backend.sign(message, key_label=ed_label)
            assert signature is not None
        
        pkcs11_backend.close()
